name: Build

on:
  push:
    tags:
      - v*  # 只有在推送标签时触发，例如 v1.0.0

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod tidy

      - name: Compile
        run: |
          go build -ldflags="-s -w" -trimpath -o device_http_control.exe

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: device_http_control.exe
          path: device_http_control.exe
          if-no-files-found: warn

  createRelease:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build  # 依赖 build job

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}  # 将 upload_url 设置为 Job 的输出

    steps:
      - name: Extract tag name
        id: extract_tag
        run: |
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          release_name: Release ${{ steps.extract_tag.outputs.tag_name }}
          body: Release of version ${{ steps.extract_tag.outputs.tag_name }}
          draft: false
          prerelease: false

  release:
    name: Upload Assets
    runs-on: ubuntu-latest
    needs: createRelease  # 依赖 createRelease job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.createRelease.outputs.upload_url }}
          asset_path: device_http_control.exe
          asset_name: device_http_control.exe
          asset_content_type: application/octet-stream